<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\Controller\\ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\Controller\\ArgumentResolver\\ServiceValueResolver.php';

return $this->services['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(['My\\TechnosBlogBundle\\Controller\\Back\\AddAdministratorController:addAdministratorAction' => function () {
    return ${($_ = isset($this->services['service_locator.h3ecyk2']) ? $this->services['service_locator.h3ecyk2'] : $this->load('getServiceLocator_H3ecyk2Service.php')) && false ?: '_'};
}, 'My\\TechnosBlogBundle\\Controller\\Front\\RegistrationController:registrationAction' => function () {
    return ${($_ = isset($this->services['service_locator.og9pbow']) ? $this->services['service_locator.og9pbow'] : $this->load('getServiceLocator_Og9pbowService.php')) && false ?: '_'};
}, 'My\\TechnosBlogBundle\\Controller\\Front\\ResettingController:resettingAction' => function () {
    return ${($_ = isset($this->services['service_locator.fivnhag']) ? $this->services['service_locator.fivnhag'] : $this->load('getServiceLocator_FivnhagService.php')) && false ?: '_'};
}, 'My\\TechnosBlogBundle\\Controller\\Back\\AddAdministratorController::addAdministratorAction' => function () {
    return ${($_ = isset($this->services['service_locator.h3ecyk2']) ? $this->services['service_locator.h3ecyk2'] : $this->load('getServiceLocator_H3ecyk2Service.php')) && false ?: '_'};
}, 'My\\TechnosBlogBundle\\Controller\\Front\\RegistrationController::registrationAction' => function () {
    return ${($_ = isset($this->services['service_locator.og9pbow']) ? $this->services['service_locator.og9pbow'] : $this->load('getServiceLocator_Og9pbowService.php')) && false ?: '_'};
}, 'My\\TechnosBlogBundle\\Controller\\Front\\ResettingController::resettingAction' => function () {
    return ${($_ = isset($this->services['service_locator.fivnhag']) ? $this->services['service_locator.fivnhag'] : $this->load('getServiceLocator_FivnhagService.php')) && false ?: '_'};
}]));
