<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7fz2ze6\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7fz2ze6/appProdProjectContainer.php') {
    touch(__DIR__.'/Container7fz2ze6.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container7fz2ze6\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container7fz2ze6\appProdProjectContainer([
    'container.build_hash' => '7fz2ze6',
    'container.build_id' => '513934f1',
    'container.build_time' => 1578883048,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7fz2ze6');
