<?php

namespace My\TechnosBlogBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use InvalidArgumentException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;



/**
 * ArticlesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticlesRepository extends EntityRepository
{
    public function paginate($page, $maxInPage, $category = null) // Ici ajouter un argument qui sera la variable SQL envoyé en post par AJAX
    {
        if(!is_numeric($page))
        {
            throw new InvalidArgumentException(
                'La valeur de l\'argument '.$page.' est incorrecte.'
            );
        }

        if($page < 1)
        {
            throw new NotFoundHttpException('La page demandée n\'existe pas');
        }

        if (!is_numeric($maxInPage)) {
            throw new InvalidArgumentException(
                'La valeur de l\'argument '.$page.' est incorrecte.'
            );
        }

            if($category)
            {
                $queryBuilder = $this->createQueryBuilder('p')
                ->where('p.category = :category')
                ->setParameter('category', $category)
                ->orderBy('p.date', 'DESC');
            }
            else
            {
                $queryBuilder = $this->createQueryBuilder('p')
                    ->orderBy('p.date', 'DESC');
            }


            $query = $queryBuilder->getQuery();

            $firstResult = ($page - 1) * $maxInPage;
            $query->setFirstResult($firstResult)->setMaxResults($maxInPage);
            $paginator = new Paginator($query);

            if (($paginator->count() <= $firstResult) && $page != 1) {
                throw new NotFoundHttpException('La page demandée n\'existe pas.');
            }

            return $paginator;

    }

    /**
     * @param \Article $title
     * @return array
     * @throws \Doctrine\DBAL\DBALException
     */
    public function getResultsForJsonReponse($title)
    {
        $sql = "SELECT * FROM Articles WHERE title LIKE :title LIMIT 0,5";
        $entMa = $this->getEntityManager();
        $sm = $entMa->getConnection()->prepare($sql);
        $sm->execute(['title' => '%' . $title . '%']);

        $arrayAjaxRequest = [];

        while ($data = $sm->fetch()) {
            array_push($arrayAjaxRequest, $data['title']);
        }

        return $arrayAjaxRequest;
    }

    /**
     * @param \Article $title
     * @return array
     * @throws \Doctrine\DBAL\DBALException
     */
    public function getResultsSearch($title)
    {
        $sql = "SELECT * FROM Articles WHERE title LIKE :title";
        $entMa = $this->getEntityManager();
        $sm = $entMa->getConnection()->prepare($sql);
        $sm->execute(['title' => '%' . $title . '%']);

        $searchCollections = [];

        while ($data = $sm->fetch()) {
            array_push($searchCollections, $data['title']);
        }

        return $searchCollections;
    }

    /**
     * @return array
     */
    public function getLastArticles()
    {
        return $query = $this->createQueryBuilder('a')
            ->setMaxResults(5)
            ->getQuery()
            ->getResult();
    }

    /**
     * @return array
     */
    public function getOthersArticles()
    {
        return $query = $this->createQueryBuilder('a')
            ->setMaxResults(3)
            ->getQuery()
            ->getResult();
    }
}
