<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRdmfru5\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRdmfru5/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRdmfru5.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRdmfru5\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerRdmfru5\appDevDebugProjectContainer([
    'container.build_hash' => 'Rdmfru5',
    'container.build_id' => '4eaea044',
    'container.build_time' => 1578961586,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRdmfru5');
