<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHicmttk\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHicmttk/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerHicmttk.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerHicmttk\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerHicmttk\appDevDebugProjectContainer([
    'container.build_hash' => 'Hicmttk',
    'container.build_id' => 'f6d8f81c',
    'container.build_time' => 1578796559,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHicmttk');
